name: CrackShotAddition
version: 2.7.3
api-version: 1.15
main: me.sul.crackshotaddition.CrackShotAddition
author: SuL
description: "CrackShot Addition"
depend:
  - CrackShot
softdepend:
  - ServerCore
  - NBTAPI
  - CustomEntity

commands:
  csa: